name: Auto Tag

on:
  push:
    branches: [main]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract version
        id: vars
        run: |
          VERSION=$(grep -m1 '^version' pyproject.toml | cut -d '"' -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create tag
        uses: actions/github-script@v7
        with:
          script: |
            const version = process.env.VERSION;
            const tagName = `v${version}`;
            const { owner, repo } = context.repo;
            const tags = await github.rest.repos.listTags({ owner, repo, per_page: 100 });
            if (!tags.data.find(t => t.name === tagName)) {
              await github.rest.git.createRef({ owner, repo, ref: `refs/tags/${tagName}`, sha: context.sha });
              core.info(`Created tag ${tagName}`);
            } else {
              core.info(`Tag ${tagName} already exists, skip.`);
            }
        env:
          VERSION: ${{ steps.vars.outputs.version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 